services:
  app:
    build: .
    command: python -u app.py
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=developer_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodbdata:
    driver: local